### ISSUE TITLE
誤字報告

### ISSUE THREAD

**Issue by maki-glenscape** [8amjp/redmine-fantasy#5]
3件の修正提案です。

- 001.md:77 s/満を辞して/満を持して/

- 012.md:18, 21 s/｜《翠玉女帝》/《翠玉女帝》/g

- 060.md:8 s/心理/真理/

ご確認よろしくお願いします。

**Comment by maki-glenscape** [comment]
2件目のルビについて、21行目のように同一行に二重山カッコが偶数個含まれると、ebooks.jsの「括弧を括弧のまま表示したい場合」が効かず、ルビ扱いになってしまうようです。

また、18行目は修正不要でした。「括弧のまま表示」構文のことを知ったのがissue報告後だったもので。

**Comment by 8amjp** [comment]
ご指摘ありがとうございます。
s/心理/真理/ の件ですが、「人間の性(さが)」という意味で使いたくて、でも深く考えてみると「心理」はちょっと違うのかなーと思い、結果「性分」という表現に変更しました。

**Comment by 8amjp** [comment]
「｜《翠玉女帝》」が同一行に複数回のパターン、スクリプトを直す気力がない……ので本文の方を変更しました。
